<?php

$title = 'Hapus customer dengan ID ' . $id_customer;
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if(!$this->adakesalahan):?>
<p>Yakin akan menghapus <?php echo $this->escapeHtml($datacustomer->nama); ?>?</p>
<?php
$url = $this->url('Order', array(
'action' => 'hapus',
'id' => $this->id_customer,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
<input type="hidden" name="id_customer" value="<?php echo $datacustomer->id_customer; ?>" />
<input type="submit" name="hapus" value="Ya" />
<input type="submit" name="hapus" value="Tidak" />
</div>
</form>
<?php else:?>
<p>Customer dengan id: <?php echo $id_customer;?> tidak ditemukan</p>
<?php endif;?>