
<?php
$title = 'Informasi Customer';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
<a href="<?php echo $this->url('Order', array('action'=>'add'));?>">
Tambah customer</a>
</p>
<table class="table">
<tr>
<th>ID</th>
<th>Nama</th>
<th>JK</th>
<th>Tgl Lahir</th>
<th>Alamat</th>
<th>Kota</th>
<th>Kode Pos</th>
<th>Telp</th>
<th>Aksi</th>
</tr>
<?php foreach ($datacustomer as $r) : ?>
 <tr>
<td><?php echo $this->escapeHtml($r->id_customer);?></td>
<td><?php echo $this->escapeHtml($r->nama);?></td>
<td><?php echo $this->escapeHtml($r->jenkel);?></td>
<td><?php echo $this->escapeHtml($r->tgl_lahir);?></td>
<td><?php echo $this->escapeHtml($r->alamat);?></td>
<td><?php echo $this->escapeHtml($r->kota);?></td>
<td><?php echo $this->escapeHtml($r->kode_pos);?></td>
<td><?php echo $this->escapeHtml($r->no_telfon);?></td>
<td>
  <a href="<?php echo $this->url('Order',
             array('action'=>'edit', 'id' => $r->id_customer));?>">Edit</a>
         <a href="<?php echo $this->url('Order',
             array('action'=>'hapus', 'id' => $r->id_customer));?>">Hapus</a>
</td>
</tr>
<?php endforeach; ?>
</table>